spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: url
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
  cors:
    origin:
      local: local
      server: server
cloud:
  aws:
    s3:
      bucket: bucket-name
      root-path: root-path
      image-directory: image-directory
    credentials:
      access-key: access-key
      secret-key: secret-key
    region:
      static: region
      auto: false
    stack:
      auto: false
youtube:
  api-key: ${YOUTUBE_API_KEY}

#인증&인가 설정 파일
jwt:
  secretKey: ${JWT_KEY}
kakao:
  auth:
    api-key: ${KAKAO_API_KEY}
    client-secret: ${KAKAO_CLIENT_SECRET}
    redirect-url: ${KAKAO_REDIRECT_URL}
admin-code: ${ADMIN_KEY}

# logback
logging:
  config: classpath:logback/Logback.xml